"""Generated public export declarations. Do not edit manually."""

# Generated by scripts/generate_core_registry.py.
PUBLIC_EXPORTS_BY_MODULE = (
    (
        "array",
        frozenset(
            "add append chunk compact concat contains count_by difference difference_by difference_with drop drop_right drop_right_while drop_while duplicates fill filter find find_index find_last_index find_median_sorted_arrays first flatten flatten_deep flatten_depth from_pairs ft_cmp_to_key ft_reduce group_by head index_by index_of initial intercalate interleave intersection intersection_by intersection_with intersperse last last_index_of map mapcat max_value min_value nth partition pluck pop power pull pull_all pull_all_by pull_all_with pull_at push range reduce reject remove rest sample shift shuffle slice_ sort sort_by sorted_index sorted_index_by sorted_index_of sorted_last_index sorted_last_index_by sorted_last_index_of sorted_uniq sorted_uniq_by splice split_at tail take take_right take_right_while take_while union union_by union_with uniq uniq_by uniq_with unshift unzip unzip_ unzip_with without xor xor_by xor_with zip zip_ zip_object zip_object_deep zip_with".split()
        ),
    ),
    (
        "object",
        frozenset(
            "all_keys apply apply_catch apply_if apply_if_not_none assign assign_with at callables clone clone_deep clone_deep_with clone_with create deep_copy defaults defaults_deep extend filter_ find_key find_last find_last_key flat_map flat_map_deep flat_map_depth for_each for_each_right for_in for_in_right functions get has includes invert invert_by invoke invoke_map is_match iterator key_by keys map_ map_keys map_object map_values map_values_deep merge merge_with nest object omit omit_by order_by pairs parse_int pick pick_by reduce_ reduce_right reductions reductions_right rename_keys result sample_size set_ set_with size to_array to_boolean to_dict to_integer to_list to_number to_pairs to_string transform unset update update_with values where".split()
        ),
    ),
    (
        "function",
        frozenset(
            "after allany anyof ary before bind bind_all compose conjoin curry curry_right debounce debounce_ defer delay disjoin enhanced_curry enhanced_curry_right enhanced_debounce enhanced_partial enhanced_partial_right filter_ flip flow flow_right invoke iterated iteratee juxtapose map_ matcher matches negate now once once_ over_args partial partial_right property_func property_of rearg reduce_ spread throttle unary wrap".split()
        ),
    ),
    (
        "utils",
        frozenset(
            "chain compress constant decompress every identity max_value memoize min_value mixin noop now random some tap times unique_id".split()
        ),
    ),
    (
        "types",
        frozenset(
            "is_arguments is_array is_array_buffer is_boolean is_data_view is_date is_element is_empty is_equal is_error is_finite is_function is_map is_nan is_null is_number is_object is_reg_exp is_set is_string is_symbol is_typed_array is_undefined is_weak_map is_weak_set".split()
        ),
    ),
    (
        "security",
        frozenset(
            "AuditLogger AuthorizationError DistributedRateLimiter InputValidationError LocalRateLimiter RateLimitBackend RateLimiter RedisRateLimitBackend ResourceLimitError SanitizationError SecurityError require_callable sanitize_string validate_callable validate_type".split()
        ),
    ),
    (
        "regex_policy",
        frozenset(
            "RegexLimits UnsafeRegex compile_bounded_regex unsafe_raw_regex".split()
        ),
    ),
    (
        "string",
        frozenset(
            "camel_case capitalize chars chop chop_right clean count_substr deburr decapitalize dedent_text ends_with ensure_ends_with ensure_starts_with escape escape_reg_exp has_substr highlight_matches human_case humanize insert_substr join kebab_case lines lower_case lower_first mask_sensitive normalize_whitespace number_format pad pad_end pad_start pascal_case predecessor prune quote reg_exp_js_match reg_exp_js_replace reg_exp_replace regex_extract regex_extract_all regex_find_all regex_replace regex_test repeat replace replace_all replace_end replace_start reverse separator_case series_phrase series_phrase_serial slice slugify snake_case split start_case starts_with strip_html_tags strip_tags substr_left substr_left_end substr_right substr_right_end successor surround swap_case title_case to_lower to_upper trim trim_end trim_start truncate unescape unquote upper_case upper_first url words".split()
        ),
    ),
    (
        "crypto",
        frozenset(
            "CRYPTO_AVAILABLE CryptoUnavailableError InvalidKey InvalidToken decrypt_string encrypt_string generate_key".split()
        ),
    ),
    (
        "template",
        frozenset("TemplateLimits html_template template".split()),
    ),
    (
        "orm",
        frozenset(
            "ARRAY AsyncEngine AsyncSession Base Boolean CheckConstraint Column Date DateTime Enum Float ForeignKey Index Integer JSON LargeBinary Numeric ORMUnavailableError Session String Text Time UniqueConstraint and_ asc async_sessionmaker bindparam create_async_engine create_async_engine_from_url create_async_sessionmaker create_sync_sessionmaker delete desc func insert or_ relationship select selectinload session_scope sessionmaker text update".split()
        ),
    ),
    (
        "db",
        frozenset(
            "BackupRestore CacheManager ConnectionError ConnectionPool DataExporter DataImporter Database DatabaseConnectionError DatabaseError DatabaseImportError EXCEL_AVAILABLE ExportError ImportError MONGODB_AVAILABLE MYSQL_AVAILABLE Migration PANDAS_AVAILABLE POSTGRES_AVAILABLE QueryBuilder QueryError REDIS_AVAILABLE UnsafeCSS UnsafeSQL bulk_insert connect quick_query table_exists unsafe_raw_css unsafe_raw_sql".split()
        ),
    ),
)

PUBLIC_SUBMODULES = frozenset(
    "array core crypto db function object orm regex_policy security string supporter template types utils".split()
)

# Later modules preserve historical wildcard collision order.
ROOT_EXPORTS = {
    _export_name: _module_name
    for _module_name, _module_exports in PUBLIC_EXPORTS_BY_MODULE
    for _export_name in _module_exports
}
