"""
File: unicorefw/crypto.py
Encryption and decryption utilities for UniCoreFW.

This module provides basic string encryption/decryption using the 'cryptography' library
(Fernet symmetric encryption). For production use, ensure that your key handling, secret
management, and error handling meet security best practices.

Copyright (C) 2024 Kenny Ngo / UniCoreFW.Org / IIPTech.info

This file is part of UniCoreFW. You can redistribute it and/or modify
it under the terms of the [BSD-3-Clause] as published by
the Free Software Foundation.
You should have received a copy of the [BSD-3-Clause] license
along with UniCoreFW. If not, see https://www.gnu.org/licenses/.
"""

try:
    from cryptography.fernet import Fernet, InvalidToken # type: ignore

    CRYPTO_AVAILABLE = True
except ImportError:
    # If cryptography isn't installed, these functions won't work
    CRYPTO_AVAILABLE = False

class InvalidToken(ValueError):
    """Raised when data sanitization fails."""
    pass

def generate_key() -> bytes:
    """
    Generate a new Fernet (AES-based) key.

    Returns:
        A randomly generated 32-byte key suitable for Fernet encryption.

    Raises:
        RuntimeError: If 'cryptography' is not installed.

    Examples:
        key = generate_key()
        encrypted_string = encrypt_string("my_secret_data", key)
        decrypted_string = decrypt_string(encrypted_string, key)
    """
    if not CRYPTO_AVAILABLE:
        raise RuntimeError("cryptography library is not installed.")
    return Fernet.generate_key() # type: ignore


def encrypt_string(plaintext: str, key: bytes) -> str:
    """
    Encrypt a plaintext string using a given Fernet key.

    Args:
        plaintext: The string to encrypt.
        key: The 32-byte key generated by 'generate_key' or shared by the user.

    Returns:
        A URL-safe base64-encoded ciphertext string.

    Raises:
        RuntimeError: If 'cryptography' is not installed.

    Examples:
        key = generate_key()
        encrypted_string = encrypt_string("my_secret_data", key)
        decrypted_string = decrypt_string(encrypted_string, key)
    """
    if not CRYPTO_AVAILABLE:
        raise RuntimeError("cryptography library is not installed.")
    f = Fernet(key) # type: ignore
    token = f.encrypt(plaintext.encode("utf-8"))
    return token.decode("utf-8")


def decrypt_string(ciphertext: str, key: bytes) -> str:
    """
    Decrypt a ciphertext string (base64-encoded token) using a given Fernet key.

    Args:
        ciphertext: The base64-encoded token from 'encrypt_string'.
        key: The same 32-byte key used to encrypt.

    Returns:
        The original plaintext string.

    Raises:
        RuntimeError: If 'cryptography' is not installed.
        ValueError: If the token is invalid or cannot be decrypted.

    Examples:
        key = generate_key()
        encrypted_string = encrypt_string("my_secret_data", key)
        decrypted_string = decrypt_string(encrypted_string, key)
    """
    if not CRYPTO_AVAILABLE:
        raise RuntimeError("cryptography library is not installed.")
    f = Fernet(key) # type: ignore
    try:
        decrypted = f.decrypt(ciphertext.encode("utf-8"))
        return decrypted.decode("utf-8")
    except InvalidToken:
        raise ValueError("Decryption failed: Invalid key or ciphertext.")
