#!/usr/bin/env python3
"""Inspect and smoke-test one wheel without importing the source checkout."""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import venv
import zipfile
from pathlib import Path, PurePosixPath
from typing import NoReturn


def fail(message: str) -> NoReturn:
    raise SystemExit(f"wheel verification failed: {message}")


def inspect_wheel(wheel_path: Path) -> None:
    """Reject unsafe paths and incomplete package contents."""
    with zipfile.ZipFile(wheel_path) as archive:
        members = archive.namelist()
        if len(members) != len(set(members)):
            fail("wheel contains duplicate member names")

        for member in members:
            path = PurePosixPath(member)
            if path.is_absolute() or ".." in path.parts or "\x00" in member:
                fail(f"wheel contains an unsafe path: {member!r}")
            if member.endswith((".pyc", ".pyo")) or "__pycache__" in path.parts:
                fail(f"wheel contains generated bytecode: {member!r}")
            if path.parts and path.parts[0] == "scripts":
                fail(f"wheel contains repository release tooling: {member!r}")

        required_suffixes = {
            "unicorefw/__init__.py",
            ".dist-info/METADATA",
            ".dist-info/RECORD",
            ".dist-info/WHEEL",
        }
        for suffix in required_suffixes:
            if not any(member.endswith(suffix) for member in members):
                fail(f"wheel is missing {suffix}")


def smoke_test_wheel(wheel_path: Path) -> None:
    """Install into a clean venv and import from an unrelated directory."""
    with tempfile.TemporaryDirectory(prefix="unicorefw-wheel-") as temp_dir:
        temp_path = Path(temp_dir)
        environment_path = temp_path / "venv"
        venv.EnvBuilder(with_pip=True, clear=True).create(environment_path)

        scripts_dir = "Scripts" if os.name == "nt" else "bin"
        python_name = "python.exe" if os.name == "nt" else "python"
        python_path = environment_path / scripts_dir / python_name

        subprocess.run(
            [
                str(python_path),
                "-I",
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--no-deps",
                str(wheel_path.resolve()),
            ],
            cwd=temp_path,
            check=True,
        )
        subprocess.run(
            [
                str(python_path),
                "-I",
                "-c",
                (
                    "import unicorefw; "
                    "assert unicorefw.__version__; "
                    "assert unicorefw.uniq([1, 1, 2]) == [1, 2]"
                ),
            ],
            cwd=temp_path,
            check=True,
        )
        subprocess.run(
            [str(python_path), "-I", "-m", "pip", "check"],
            cwd=temp_path,
            check=True,
        )


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        fail("usage: verify_wheel.py path/to/package.whl")
    wheel_path = Path(argv[1])
    if not wheel_path.is_file() or wheel_path.suffix != ".whl":
        fail(f"wheel does not exist: {wheel_path}")
    inspect_wheel(wheel_path)
    smoke_test_wheel(wheel_path)
    print(f"wheel verified: {wheel_path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
